#!/usr/bin/env bash

set -Eeuo pipefail

readonly M1_REPOSITORY_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
readonly M1_ARTIFACT_ROOT="${M1_ARTIFACT_ROOT:-${M1_REPOSITORY_ROOT}/artifacts/m1-gate}"
readonly M1_BASE_COMMIT="${M1_BASE_COMMIT:-65c94cc991d3549137de51827edd66b473cc8e31}"
readonly M1_APP_URL="${M1_APP_URL:-http://127.0.0.1:3000}"
readonly M1_APP_LOG="${M1_ARTIFACT_ROOT}/application.log"
readonly M1_APP_PID_FILE="${M1_ARTIFACT_ROOT}/application.pid"
readonly M1_WORKER_LOG="${M1_ARTIFACT_ROOT}/worker.log"
readonly M1_WORKER_PID_FILE="${M1_ARTIFACT_ROOT}/worker.pid"
readonly M1_SUPABASE_WORKDIR="${SUPABASE_WORKDIR:-${M1_REPOSITORY_ROOT}/apps/portal}"
export SUPABASE_WORKDIR="${M1_SUPABASE_WORKDIR}"

M1_SUPABASE_STARTED=0
M1_APP_STARTED=0
M1_WORKER_STARTED=0
M1_FAILURE_STATE=BLOCKED
M1_ENV_FILE=""

mkdir -p "${M1_ARTIFACT_ROOT}"
rm -f "${M1_APP_PID_FILE}"
rm -f "${M1_WORKER_PID_FILE}"

record_summary() {
  local state="$1"
  {
    echo "state=${state}"
    echo "commit=$(git -C "${M1_REPOSITORY_ROOT}" rev-parse HEAD)"
    echo "date_utc=$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  } > "${M1_ARTIFACT_ROOT}/summary.txt"
}

cleanup() {
  local exit_code=$?

  if [[ "${M1_WORKER_STARTED}" == "1" ]] && [[ -f "${M1_WORKER_PID_FILE}" ]]; then
    kill "$(<"${M1_WORKER_PID_FILE}")" 2>/dev/null || true
  fi

  if [[ "${M1_APP_STARTED}" == "1" ]] && [[ -f "${M1_APP_PID_FILE}" ]]; then
    kill "$(<"${M1_APP_PID_FILE}")" 2>/dev/null || true
  fi

  if [[ "${M1_SUPABASE_STARTED}" == "1" ]] && [[ "${M1_KEEP_SERVICES:-0}" != "1" ]]; then
    pnpm --filter @father-empowering/portal exec supabase stop \
      --workdir "${M1_SUPABASE_WORKDIR}" --no-backup >/dev/null 2>&1 || true
  fi

  if [[ -n "${M1_ENV_FILE}" ]] && [[ -f "${M1_ENV_FILE}" ]]; then
    rm -f -- "${M1_ENV_FILE}"
  fi

  if [[ ${exit_code} -ne 0 ]]; then
    record_summary "${M1_FAILURE_STATE}"
  fi
}

trap cleanup EXIT

run_logged() {
  local log_name="$1"
  shift
  "$@" 2>&1 | tee "${M1_ARTIFACT_ROOT}/${log_name}.log"
}

require_command() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "BLOCKED: commande requise absente: $1" >&2
    record_summary BLOCKED
    exit 2
  fi
}

verify_no_skipped_m1_tests() {
  if rg -n --glob '*.{ts,tsx,js,mjs,sql}' \
    '(describe|it|test)\.(skip|todo)|\bskip\s*\(|\btodo\s*\(' \
    apps/portal/tests apps/portal/supabase/tests/quality 2>/dev/null; then
    echo "FAIL: un test M1 obligatoire est ignoré ou TODO." >&2
    return 1
  fi
}

verify_legacy_unchanged() {
  local legacy_paths=(
    index.html
    sw.js
    site.webmanifest
    i18n.js
    generate-portal.js
    clients
    templates/client-package
    training-program.json
    nutrition-program.json
    version.json
  )

  git -C "${M1_REPOSITORY_ROOT}" diff --exit-code "${M1_BASE_COMMIT}" -- "${legacy_paths[@]}"
}

verify_artifacts_safe() {
  if rg --quiet -i \
    '#token=[A-Za-z0-9_-]{32,}|"(invitationToken|opaqueToken|rawToken|otp)"[[:space:]]*:' \
    "${M1_ARTIFACT_ROOT}" 2>/dev/null; then
    : > "${M1_ARTIFACT_ROOT}/UNSAFE_ARTIFACTS_DO_NOT_UPLOAD"
    echo "FAIL: un artefact M1 contient un motif de jeton ou OTP brut." >&2
    return 1
  fi
}

export_local_supabase_environment() {
  M1_ENV_FILE="$(mktemp "${TMPDIR:-/tmp}/father-empowering-m1-env.XXXXXX")"
  node "${M1_REPOSITORY_ROOT}/scripts/m1-supabase-env.mjs" \
    "${M1_ENV_FILE}"

  # The file contains credentials generated by the disposable local Supabase
  # instance only. The helper rejects non-loopback URLs.
  set -a
  # shellcheck disable=SC1091
  source "${M1_ENV_FILE}"
  set +a
}

start_application() {
  pnpm --filter @father-empowering/portal start \
    >"${M1_APP_LOG}" 2>&1 &
  echo "$!" > "${M1_APP_PID_FILE}"
  M1_APP_STARTED=1

  node "${M1_REPOSITORY_ROOT}/scripts/m1-wait-for-http.mjs" \
    "${M1_APP_URL}" 60000
}

start_worker() {
  pnpm --filter @father-empowering/portal worker:m1 \
    >"${M1_WORKER_LOG}" 2>&1 &
  echo "$!" > "${M1_WORKER_PID_FILE}"
  M1_WORKER_STARTED=1

  # Detect an immediately failing worker before any email-dependent test.
  sleep 1
  if ! kill -0 "$(<"${M1_WORKER_PID_FILE}")" 2>/dev/null; then
    echo "BLOCKED: le worker M1 n'est pas resté actif." >&2
    return 2
  fi
}

cd "${M1_REPOSITORY_ROOT}"

require_command node
require_command pnpm
require_command git
require_command docker
require_command rg

{
  node --version
  pnpm --version
  pnpm --filter @father-empowering/portal exec supabase --version
  pnpm --filter @father-empowering/portal exec playwright --version
} > "${M1_ARTIFACT_ROOT}/versions.txt"

M1_FAILURE_STATE=FAIL
run_logged legacy verify_legacy_unchanged
run_logged static verify_no_skipped_m1_tests
run_logged unit pnpm test:unit
run_logged lint pnpm lint
run_logged typecheck pnpm typecheck

M1_FAILURE_STATE=BLOCKED
run_logged supabase-start pnpm --filter @father-empowering/portal exec supabase start \
  --workdir "${M1_SUPABASE_WORKDIR}"
M1_SUPABASE_STARTED=1
export_local_supabase_environment

M1_FAILURE_STATE=FAIL
run_logged rls pnpm --filter @father-empowering/portal exec supabase test db quality \
  --workdir "${M1_SUPABASE_WORKDIR}"
run_logged build pnpm build

start_application
M1_FAILURE_STATE=BLOCKED
start_worker
M1_FAILURE_STATE=FAIL
run_logged integration pnpm --filter @father-empowering/portal test:integration
run_logged e2e pnpm --filter @father-empowering/portal exec playwright test \
  --config apps/portal/tests/e2e/playwright.config.ts
run_logged artifact-safety verify_artifacts_safe

record_summary PASS
echo "PASS: gate M1 réussi sur $(git rev-parse --short HEAD)."
